#!/usr/bin/env python3

import rospy
from std_msgs.msg import Int32

rospy.init_node('number_publisher')

pub = rospy.Publisher('number_topic', Int32, queue_size=10)

rate = rospy.Rate(10)



while not rospy.is_shutdown():

    mess = int(input("Enter the number : "))
    pub.publish(mess)
    
    rate.sleep()









# def callbackfun(data):
# 	print(data.data)
# 	return data.data


# def inp():
#     desti = input('Enter the table No : ').split(',')
#     return desti

# # def confor():
# #     com_me = input("Please Confirm your order with y or n")
# #     if (com_me == 'y'):
# #         return True
# #     else :
# #         return False


# def timerr():
#     try:
#         c = inputimeout(prompt='Please Confirm your order with y or n :  ', timeout=10)
#         if (c == 'y'):
#             return True
#         else :
#             return False
#     except TimeoutOccurred:
#         c = 'timeout'
#         return False
    




# def algo(desi):
#     dum = True
#     movv = movee(4)
#     print("reached "+ locations[4])
#     for ii in desi:
#         ii = int(ii)
#         chec = movee(ii)
#         if(dum and chec):
#             dum = True
#         else:
#             dum = False
#     if(dum):
#         movee(0)
#     else:
#         movee(4)
#         movee(0)

#     print("reached "+ locations[0])









# if __name__ == "__main__":
#     while not rospy.is_shutdown():
#         place = inp()
#         algo(place)
#         # rospy.spin()
#     # except rospy.ROSInterruptException:
#     #     pass
    