arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1j
    - arm2j
    - arm3j
    - arm4j
  gains:
    arm1j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm4j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
end_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - end1j
    - end2j
  gains:
    end1j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    end2j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
